name: Build Binary and Commit to Repo

on:
  push:
    branches:
      - master
    paths:
      - op.py
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Build binary
        run: |
          ./build.sh 

      - name: Commit binary to repository
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add dist/
          git commit -m "Add latest binary build"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
